name       : inkscape
homepage   : https://inkscape.org/
version    : 1.0.2
release    : 34
source     :
    - https://inkscape.org/gallery/item/23820/inkscape-1.0.2.tar.xz : da3e230511a08cbf21e86710d161458594fea87867e9157b67ed01a04ea2798a
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Inkscape is an open-source vector graphics editor similar to Adobe Illustrator, Corel Draw, Freehand, or Xara X
description: |
    Inkscape is an open-source vector graphics editor similar to Adobe Illustrator, Corel Draw, Freehand, or Xara X. What sets Inkscape apart is its use of Scalable Vector Graphics (SVG), an open XML-based W3C standard, as the native format.
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(gdl-3.0)
    - pkgconfig(gsl)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
    - pkgconfig(poppler)
    - pkgconfig(popt)
    - double-conversion-devel
    - libboost-devel
    - numpy
    - potrace-devel
    - python-lxml
rundeps    :
    - numpy
    - python-lxml
    - scour
patterns   :
    - docs : [/usr/share/inkscape/examples, /usr/share/inkscape/tutorials, /usr/share/doc]
setup      : |
    %apply_patches
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
