name       : inkscape
homepage   : https://inkscape.org/
version    : '1.0'
release    : 27
source     :
    - https://inkscape.org/gallery/item/18460/inkscape-1.0.tar.xz : 89c123d1a62ac52db6a08fe3be730584411b89a88ecc528a410b4f3fa53f94bb
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Inkscape is an open-source vector graphics editor similar to Adobe Illustrator, Corel Draw, Freehand, or Xara X
description: |
    Inkscape is an open-source vector graphics editor similar to Adobe Illustrator, Corel Draw, Freehand, or Xara X. What sets Inkscape apart is its use of Scalable Vector Graphics (SVG), an open XML-based W3C standard, as the native format.
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(gdl-3.0)
    - pkgconfig(gsl)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
    - pkgconfig(poppler)
    - pkgconfig(popt)
    - double-conversion-devel
    - libboost-devel
    - numpy
    - potrace-devel
    - python-lxml
rundeps    :
    - numpy
    - python-lxml
patterns   :
    - docs : [/usr/share/inkscape/examples, /usr/share/inkscape/tutorials, /usr/share/doc]
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
