name       : inkscape
homepage   : https://inkscape.org/
version    : 1.0.1
release    : 32
source     :
    - https://inkscape.org/gallery/item/21571/inkscape-1.0.1.tar.xz : cf9295edf46a633caf3aac0562364a24aef7cd6294601365aca38aeead2d57c2
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Inkscape is an open-source vector graphics editor similar to Adobe Illustrator,
    Corel Draw, Freehand, or Xara X
description: |
    Inkscape is an open-source vector graphics editor similar to Adobe Illustrator, Corel Draw, Freehand, or Xara X. What sets Inkscape apart is its use of Scalable Vector Graphics (SVG), an open XML-based W3C standard, as the native format.
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(gdl-3.0)
    - pkgconfig(gsl)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
    - pkgconfig(poppler)
    - pkgconfig(popt)
    - double-conversion-devel
    - libboost-devel
    - numpy
    - potrace-devel
    - python-lxml
rundeps    :
    - numpy
    - python-lxml
    - scour
patterns   :
    - docs : [/usr/share/inkscape/examples, /usr/share/inkscape/tutorials, /usr/share/doc]
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
