name       : inkscape
version    : 0.91
release    : 8
source     :
    - https://inkscape.org/en/gallery/item/3860/inkscape-0.91.tar.bz2 : 4d901f8a9e1924404e797ad23b8b0c495a9d155448816d95a55974314e1f141b
license    : GPL-2.0
component  : graphics
summary    : Inkscape is an open-source vector graphics editor similar to Adobe Illustrator, Corel Draw, Freehand, or Xara X.
description: |
    Inkscape is an open-source vector graphics editor similar to Adobe Illustrator, Corel Draw, Freehand, or Xara X. What sets Inkscape apart is its use of Scalable Vector Graphics (SVG), an open XML-based W3C standard, as the native format.
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(bdw-gc)
    - pkgconfig(cairo)
    - pkgconfig(dbus-1)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(gsl)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libxslt)
    - pkgconfig(poppler)
    - pkgconfig(popt)
    - pkgconfig(python-2.7)
    - pkgconfig(x11)
    - gvfs-devel
    - intltool
    - libboost-devel
    - numpy
    - python-lxml
rundeps    :
    - numpy
    - python
    - python-lxml
patterns   :
    - docs: [/usr/share/inkscape/examples,/usr/share/inkscape/tutorials,/usr/share/doc]
setup      : |
    sed -i 's|/usr/bin/python\>|/usr/bin/python2|g' cxxtest/*.py
    sed -i 's|/usr/bin/env python\>|/usr/bin/env python2|g' share/*/{test/,}*.py
    sed -i 's|"python" },|"python2" },|g' src/extension/implementation/script.cpp
    sed -i 's|python -c|python2 -c|g' configure share/extensions/uniconv*.py
    sed -i 's|"python"|"python2"|g' src/main.cpp

    CXXFLAGS+=' -std=c++11'
    %configure \
        --disable-dependency-tracking \
        --enable-lcms \
        --enable-poppler-cairo
build      : |
    %make
install    : |
    %make_install
