name       : inkscape
homepage   : https://inkscape.org/
version    : 1.2.2
release    : 58
source     :
    - https://media.inkscape.org/dl/resources/file/inkscape-1.2.2.tar.xz : a0c7fd0d03c0a21535e648ef301dcf80dd7cfc1f3545e51065fbf1ba3ee8a5c4
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
    - MPL-1.1
component  : multimedia.graphics
summary    : Inkscape is an open-source vector graphics editor similar to Adobe Illustrator, Corel Draw, Freehand, or Xara X
description: |
    Inkscape is an open-source vector graphics editor similar to Adobe Illustrator, Corel Draw, Freehand, or Xara X. What sets Inkscape apart is its use of Scalable Vector Graphics (SVG), an open XML-based W3C standard, as the native format.
clang      : yes
builddeps  :
    - pkgconfig(bdw-gc)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gspell-1)
    - pkgconfig(gsl)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcdr-0.1)
    - pkgconfig(libvisio-0.1)
    - pkgconfig(libexif)
    - pkgconfig(libjpeg)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
    - pkgconfig(poppler)
    - pkgconfig(popt)
    - pkgconfig(2geom)
    - double-conversion-devel
    - libboost-devel
    - numpy
    - potrace-devel
    - python-lxml
rundeps    :
    - numpy
    - python-cssselect
    - python-lxml
    - python-pillow
    - scour
setup      : |
    %cmake_ninja -DWITH_DBUS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/inkscape/doc
    rm -rf $installdir/usr/share/inkscape/extensions/{README,STYLEGUIDE,TESTING}.md
    rm -rf $installdir/usr/share/inkscape/themes/LICENSE.txt
    rm -rf $installdir/usr/share/inkscape/themes/README.md
patterns   :
    - docs :
        - /usr/share/inkscape/examples
        - /usr/share/inkscape/extensions/docs/
        - /usr/share/inkscape/tutorials
