name       : inkscape
homepage   : https://inkscape.org/
version    : 0.92.4
release    : 25
source     :
    - https://media.inkscape.org/dl/resources/file/inkscape-0.92.4.tar.bz2 : 57ec2da8177b36614a513e2822efd73af721e690f7ddc6bd0a5fbb1525b4515e
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Inkscape is an open-source vector graphics editor similar to Adobe Illustrator,
    Corel Draw, Freehand, or Xara X
description: |
    Inkscape is an open-source vector graphics editor similar to Adobe Illustrator, Corel Draw, Freehand, or Xara X. What sets Inkscape apart is its use of Scalable Vector Graphics (SVG), an open XML-based W3C standard, as the native format.
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(bdw-gc)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gsl)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libxslt)
    - pkgconfig(poppler)
    - pkgconfig(popt)
    - pkgconfig(x11)
    - intltool
    - libboost-devel
    - numpy
    - potrace-devel
    - python-lxml
rundeps    :
    - numpy
    - python
    - python-lxml
patterns   :
    - docs : [/usr/share/inkscape/examples, /usr/share/inkscape/tutorials, /usr/share/doc]
setup      : |
    CXXFLAGS+=' -std=c++11'
    %autogen \
        --disable-static \
        --enable-lcms \
        --enable-poppler-cairo \
        --enable-dbusapi
build      : |
    %make
install    : |
    %make_install
