name       : inkscape
homepage   : https://inkscape.org/en/
version    : 0.92.2
release    : 19
source     :
    - https://media.inkscape.org/dl/resources/file/inkscape-0.92.2.tar.bz2 : a628d0e04c254e9840947e6d866974f92c68ae31631a38b94d9b65e5cd84cfd3
license    : GPL-2.0
component  : multimedia.graphics
summary    : Inkscape is an open-source vector graphics editor similar to Adobe Illustrator,
    Corel Draw, Freehand, or Xara X.
description: |
    Inkscape is an open-source vector graphics editor similar to Adobe Illustrator, Corel Draw, Freehand, or Xara X. What sets Inkscape apart is its use of Scalable Vector Graphics (SVG), an open XML-based W3C standard, as the native format.
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(bdw-gc)
    - pkgconfig(cairo)
    - pkgconfig(dbus-1)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(gsl)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libexif)
    - pkgconfig(libxslt)
    - pkgconfig(poppler)
    - pkgconfig(popt)
    - pkgconfig(python-2.7)
    - pkgconfig(x11)
    - gvfs-devel
    - intltool
    - libboost-devel
    - numpy
    - potrace-devel
    - python-lxml
rundeps    :
    - numpy
    - python
    - python-lxml
patterns   :
    - docs : [/usr/share/inkscape/examples, /usr/share/inkscape/tutorials, /usr/share/doc]
setup      : |
    %patch -p1 < $pkgfiles/poppler-0.58.patch
    ./autogen.sh # Yes, I know we have autogen macro, but that calls configure
    sed -i 's|/usr/bin/python\>|/usr/bin/python2|g' cxxtest/*.py
    sed -i 's|/usr/bin/env python\>|/usr/bin/env python2|g' share/*/{test/,}*.py
    sed -i 's|"python" },|"python2" },|g' src/extension/implementation/script.cpp
    sed -i 's|python -c|python2 -c|g' configure share/extensions/uniconv*.py
    sed -i 's|"python"|"python2"|g' src/main.cpp

    CXXFLAGS+=' -std=c++11'
    %configure \
        --disable-dependency-tracking \
        --enable-lcms \
        --enable-poppler-cairo
build      : |
    %make
install    : |
    %make_install
